// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHPIuWdoOPmDKT4EJCoqHY72ftORBMgI',
    appId: '1:1094929861292:web:bd4d352c06b2cd9f9bed09',
    messagingSenderId: '1094929861292',
    projectId: 'crisis-hackfest',
    authDomain: 'crisis-hackfest.firebaseapp.com',
    storageBucket: 'crisis-hackfest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqhhSJN6iVlVJ_Q24Bfx4sIlhiK720VF4',
    appId: '1:1094929861292:android:1ae836dcd6f3125a9bed09',
    messagingSenderId: '1094929861292',
    projectId: 'crisis-hackfest',
    storageBucket: 'crisis-hackfest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA27ib28EkS0ozasGGLRcZ9yr1seLw_lso',
    appId: '1:1094929861292:ios:e18257681b926da79bed09',
    messagingSenderId: '1094929861292',
    projectId: 'crisis-hackfest',
    storageBucket: 'crisis-hackfest.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA27ib28EkS0ozasGGLRcZ9yr1seLw_lso',
    appId: '1:1094929861292:ios:e18257681b926da79bed09',
    messagingSenderId: '1094929861292',
    projectId: 'crisis-hackfest',
    storageBucket: 'crisis-hackfest.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClHPIuWdoOPmDKT4EJCoqHY72ftORBMgI',
    appId: '1:1094929861292:web:83c89e9236152da09bed09',
    messagingSenderId: '1094929861292',
    projectId: 'crisis-hackfest',
    authDomain: 'crisis-hackfest.firebaseapp.com',
    storageBucket: 'crisis-hackfest.appspot.com',
  );
}
